<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9bvd0i3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9bvd0i3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9bvd0i3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9bvd0i3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9bvd0i3\appDevDebugProjectContainer(array(
    'container.build_hash' => '9bvd0i3',
    'container.build_id' => '6a949550',
    'container.build_time' => 1544123622,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9bvd0i3');
