<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \AppBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'dateCreation', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'id_article', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'qty_f1', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'montant_f1', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'qty_f2', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'montant_f2', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'panier', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'article');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'dateCreation', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'id_article', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'qty_f1', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'montant_f1', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'qty_f2', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'montant_f2', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'panier', '' . "\0" . 'AppBundle\\Entity\\Commande' . "\0" . 'article');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArticle($idArticle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArticle', array($idArticle));

        return parent::setIdArticle($idArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArticle', array());

        return parent::getIdArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtyF1($qtyF1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtyF1', array($qtyF1));

        return parent::setQtyF1($qtyF1);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtyF1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtyF1', array());

        return parent::getQtyF1();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantF1($montantF1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantF1', array($montantF1));

        return parent::setMontantF1($montantF1);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantF1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantF1', array());

        return parent::getMontantF1();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtyF2($qtyF2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtyF2', array($qtyF2));

        return parent::setQtyF2($qtyF2);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtyF2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtyF2', array());

        return parent::getQtyF2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantF2($montantF2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantF2', array($montantF2));

        return parent::setMontantF2($montantF2);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantF2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantF2', array());

        return parent::getMontantF2();
    }

    /**
     * {@inheritDoc}
     */
    public function setPanier(\AppBundle\Entity\Panier $panier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPanier', array($panier));

        return parent::setPanier($panier);
    }

    /**
     * {@inheritDoc}
     */
    public function getPanier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPanier', array());

        return parent::getPanier();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticle(\AppBundle\Entity\Article $article = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticle', array($article));

        return parent::setArticle($article);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticle', array());

        return parent::getArticle();
    }

}
